#!/bin/bash
#### Will Pierce
#### August 7, 2014
#### JSS Extension Attribute
#### Display Name - ScreenSaver-AskForPasswordDelay
#### Description - When will the Screen Saver ask the user for a password?
#### Data Type - String
#### Inventory Display - OS
#### Input Type - Script

# Get the Username of the currently logged user
loggedInUser=`/bin/ls -l /dev/console | /usr/bin/awk '{ print $3 }'`

## Read the askForPasswordDelay key set it as var
askForPasswordDelay=`defaults read /Library/Managed\ Preferences/$loggedInUser/com.apple.screensaver.plist askForPasswordDelay`

if [ "$askForPasswordDelay" == "60" ]; then
	result="1 min"
else
if [ "$askForPasswordDelay" -ne "60" ]; then
	result="Not 1 min"
else
if [ "$askForPasswordDelay" == "" ]; then
	result="Domain or Key Not Found"
fi
fi
fi
echo "<result>$result</result>"
