#!/bin/bash
#### Will Pierce
#### August 7, 2014
#### JSS Extension Attribute
#### Display Name
#### Description - Will the Screen Saver ask the user for a password?
#### Data Type - String
#### Inventory Display - OS
#### Input Type - Script


# Get the Username of the currently logged user
loggedInUser=`/bin/ls -l /dev/console | /usr/bin/awk '{ print $3 }'`

## Read the askForPassword key set it as var
askForPassword=`defaults read /Library/Managed\ Preferences/$loggedInUser/com.apple.screensaver.plist askForPassword`

if [ "$askForPassword" == "1" ]; then
	result="Yes"
else
if [ "$askForPassword" == "0" ]; then
	result="No"
else
if [ "$askForPassword" == "" ]; then
	result="Domain or Key Not Found"
fi
fi
fi
echo "<result>$result</result>"
